stages:
  - build

build-code-job:
  stage: build
  tags:
    - build
  script:
    - ls -lha event
    - ls -lha ticket
    - echo "Building the project "
    - cd docker-compose
    - docker-compose create --build
