stages:
  - build-and-test
  - create-image

lint-test:
  stage: build-and-test
  tags:
    - build-and-test
  image: node:alpine
  script:
    - cd event
    - npm i
    - npm run lint-and-test
    - cd ../ticket
    - npm i
    - npm run lint-and-test

transpile-code:
  stage: build-and-test
  tags:
    - build-and-test
  image: node:alpine
  script:
    - cd event
    - npm i
    - npm run build
    - cd ../ticket
    - npm i
    - npm run build
  artifacts:
    paths:
      - event/build
      - ticket/build

create-image:
  stage: create-image
  tags:
    - create-image
  script:
    - cd docker-compose
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.inf.unibz.it
    - docker-compose build
    - docker-compose push

test_services:
  stage: create-image
  tags:
    - create-image
  script:
    - docker-compose pull
    - docker-compose up -d
    - docker-compose ps
    - docker-compose logs -f event
