stages:
  - build

build-code-job:
  stage: build
  image: node:alpine
  tags:
    - build
  script:
    - cd event
    - npm run build
    - cd ../ticket
    - npm run build
    - cd ../docker-compose
    - docker-compose create --build
