stages:
  - build-and-test
  - create-image

lint-test:
  stage: build-and-test
  tags:
    - build-and-test
  image: node:alpine
  script:
    - cd event
    - npm i
    - npm run lint-and-test
    - cd ../ticket
    - npm i
    - npm run lint-and-test

transpile-code:
  stage: build-and-test
  tags:
    - build-and-test
  image: node:alpine
  script:
    - cd event
    - npm i
    - npm run build
    - cd ../ticket
    - npm i
    - npm run build
  artifacts:
    paths:
      - event/build
      - ticket/build

create-image:
  stage: create-image
  tags:
    - create-image
  script:
    - cd docker-compose
    - docker-compose create --build
