services:
  consul:
    image: consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect=1 -ui -client 0.0.0.0"
  message-queue:
    image: rabbitmq:latest
    ports:
      - "15672:15672"
    volumes:
      - ./rabbitmq:/etc/rabbitmq
    depends_on:
      - "consul"
  ticket:
    image: teilkasko/tickent-ticket
    volumes:
      - ./storage/ticket:/app/storage
    depends_on:
      - "consul"
      - "message-queue"
  event:
    image: teilkasko/tickent-event
    volumes:
      - ./storage/event:/app/storage
    depends_on:
      - "consul"
      - "message-queue"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/api_gateway.conf:/etc/nginx/api_gateway.conf
      - ./nginx/api_backends.conf:/etc/nginx/api_backends.conf
      - ./nginx/api_json_errors.conf:/etc/nginx/api_json_errors.conf
      - ./nginx/api_conf.d:/etc/nginx/api_conf.d
    ports:
      - "8080:80"
    depends_on:
      - "event"
      - "ticket"
