services:
  consul:
    image: consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect=1 -ui -client 0.0.0.0"
  message-queue:
    image: rabbitmq:latest
    volumes:
      - ./rabbitmq:/etc/rabbitmq
    depends_on:
      - "consul"
  event:
    image: teilkasko/tickent-event
    ports:
      - "3001:3001"
    volumes:
      - ./storage/event:/app/storage
    depends_on:
      - "consul"
  ticket:
    image: teilkasko/tickent-ticket
    ports:
      - "3002:3002"
    volumes:
      - ./storage/ticket:/app/storage
    depends_on:
      - "consul"
